blogger_blog:
    resource: "@BloggerBlogBundle/Resources/config/routing.yml"
    prefix:   /blogger

geekhub_task8:
    resource: "@GeekhubTask8Bundle/Resources/config/routing.yml"
    prefix:   /task8


